package mp2

//go:generate stringer -type=Object
type Object uint8

const (
	XXX              Object = iota // 0
	AlchemyLab                     // 1
	_                              // 2
	_                              // 3
	Skeleton                       // 4
	DaemonCave                     // 5
	_                              // 6
	FaerieRing                     // 7
	_                              // 8
	_                              // 9
	Gazebo                         // 10
	_                              // 11
	Graveyard                      // 12
	ArchersHouse                   // 13
	_                              // 14
	DwarfCottage                   // 15
	PeasantHut                     // 16
	_                              // 17
	_                              // 18
	_                              // 19
	DragonCity                     // 20
	LightHouse                     // 21
	WaterWheel                     // 22
	Mines                          // 23
	_                              // 24
	Obelisk                        // 25
	Oasis                          // 26
	_                              // 27
	Coast1                         // 28
	Sawmill                        // 29
	Oracle                         // 30
	_                              // 31
	ShipWreck                      // 32
	_                              // 33
	DesertTent                     // 34
	Castle                         // 35
	StoneLights                    // 36
	WagonCamp                      // 37
	_                              // 38
	_                              // 39
	Windmill                       // 40
	_                              // 41
	_                              // 42
	_                              // 43
	_                              // 44
	_                              // 45
	_                              // 46
	_                              // 47
	RandomTown                     // 48
	RandomCastle                   // 49
	_                              // 50
	_                              // 51
	_                              // 52
	_                              // 53
	_                              // 54
	_                              // 55
	Coast2                         // 56
	Coast3                         // 57
	WatchTower                     // 58
	TreeHouse                      // 59
	TreeCity                       // 60
	Ruins                          // 61
	Fort                           // 62
	TradingPost                    // 63
	AbandonedMine                  // 64
	_                              // 65
	_                              // 66
	_                              // 67
	TreeOfKnowledge                // 68
	DoctorHut                      // 69
	Temple                         // 70
	HillFort                       // 71
	HalflingHole                   // 72
	MercenaryCamp                  // 73
	_                              // 74
	_                              // 75
	Pyramid                        // 76
	CityOfTheDead                  // 77
	Excavation                     // 78
	Sphinx                         // 79
	_                              // 80
	Coast4                         // 81
	ArtesianSpring                 // 82
	TrollBridge                    // 83
	_                              // 84
	WitchsHut                      // 85
	Xanadu                         // 86
	Cave                           // 87
	_                              // 88
	MagellansMaps                  // 89
	_                              // 90
	DerelictShip                   // 91
	_                              // 92
	_                              // 93
	MagicWell                      // 94
	_                              // 95
	ObservationTower               // 96
	FreemansFoundry                // 97
	_                              // 98
	Coast5                         // 99
	Coast6                         // 100
	Coast7                         // 101
	Coast8                         // 102
	Coast9                         // 103
	Coast10                        // 104
	Coast11                        // 105
	Coast12                        // 106
	Coast13                        // 107
	Coast14                        // 108
	Coast15                        // 109
	Coast16                        // 110
	Coast17                        // 111
	Coast18                        // 112
	Coast19                        // 113
	Arena                          // 114
	BarrowMounds                   // 115
	Mermaid                        // 116
	Sirens                         // 117
	HutMagi                        // 118
	EyeMagi                        // 119
	TravellerTent                  // 120
	_                              // 121
	_                              // 122
	Jail                           // 123
	FireAltar                      // 124
	AirAltar                       // 125
	EarthAltar                     // 126
	WaterAltar                     // 127
	Coast20                        // 128
	Coast21                        // 129
	Coast22                        // 130
	Coast23                        // 131
	Coast24                        // 132
	Coast25                        // 133
	Coast26                        // 134
	Coast27                        // 135
	Coast28                        // 136
	Coast29                        // 137
	Coast30                        // 138
	Coast31                        // 139
	Coast32                        // 140
	Coast33                        // 141
	Coast34                        // 142
	Coast35                        // 143
	Coast36                        // 144
	_                              // 145
	_                              // 146
	Coast37                        // 147
	Coast38                        // 148
	Coast39                        // 149
	Coast40                        // 150
	Coast41                        // 151
	Coast42                        // 152
	Coast43                        // 153
	Coast44                        // 154
	Coast45                        // 155
	_                              // 156
	Coast46                        // 157
	Coast47                        // 158
	Coast48                        // 159
	Coast49                        // 160
	_                              // 161
	Coast50                        // 162
	Coast51                        // 163
	Coast52                        // 164
	Coast53                        // 165
	_                              // 166
	Coast54                        // 167
	Coast55                        // 168
	Coast56                        // 169
	_                              // 170
	Coast57                        // 171
	Coast58                        // 172
	Coast59                        // 173
	Coast60                        // 174
	Coast61                        // 175
	Coast62                        // 176
	Coast63                        // 177
	_                              // 178
	Coast64                        // 179
	Coast65                        // 180
	Coast66                        // 181
	Coast67                        // 182
	Coast68                        // 183
	_                              // 184
	_                              // 185
	Coast69                        // 186
	Coast70                        // 187
	Coast71                        // 188
	Coast72                        // 189
	Coast73                        // 190
	Coast74                        // 191
	Coast75                        // 192
	Coast76                        // 193
	Coast77                        // 194
	Coast78                        // 195
	Coast79                        // 196
	Coast80                        // 197
	Coast81                        // 198
	Coast82                        // 199
	Coast83                        // 200
	Coast84                        // 201
	Coast85                        // 202
	Coast86                        // 203
	Coast87                        // 204
	Coast88                        // 205
	Coast89                        // 206
	Coast90                        // 207
	Coast91                        // 208
	_                              // 209
	Coast92                        // 210
	Coast93                        // 211
	Coast94                        // 212
	Coast95                        // 213
	Coast96                        // 214
	Coast97                        // 215
	Coast98                        // 216
	Coast99                        // 217
	Coast100                       // 218
	Coast101                       // 219
	Coast102                       // 220
	Coast103                       // 221
	Coast104                       // 222
	Coast105                       // 223
	Coast106                       // 224
	Coast107                       // 225
	_                              // 226
	_                              // 227
	_                              // 228
	_                              // 229
	_                              // 230
	_                              // 231
	_                              // 232
	Coast108                       // 233
	AlchemyTower                   // 234
	Stables                        // 235
	Coast109                       // 236
	Coast110                       // 237
	Coast111                       // 238
	Coast112                       // 239
	Coast113                       // 240
	Coast114                       // 241
	Coast115                       // 242
	Coast116                       // 243
	Coast117                       // 244
	Coast128                       // 245
	Coast129                       // 246
	Coast130                       // 247
	Coast131                       // 248
	_                              // 249
	_                              // 250
	Coast132                       // 251
	Coast133                       // 252
	Coast134                       // 253
	Coast135                       // 254
	Coast136                       // 255
)
