// Code generated by "stringer -type=Object"; DO NOT EDIT.

package mp2

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AlchemyLab-1]
	_ = x[Skeleton-4]
	_ = x[DaemonCave-5]
	_ = x[FaerieRing-7]
	_ = x[Gazebo-10]
	_ = x[Graveyard-12]
	_ = x[ArchersHouse-13]
	_ = x[DwarfCottage-15]
	_ = x[PeasantHut-16]
	_ = x[DragonCity-20]
	_ = x[LightHouse-21]
	_ = x[WaterWheel-22]
	_ = x[Mines-23]
	_ = x[Obelisk-25]
	_ = x[Oasis-26]
	_ = x[Sawmill-29]
	_ = x[Oracle-30]
	_ = x[ShipWreck-32]
	_ = x[DesertTent-34]
	_ = x[Castle-35]
	_ = x[StoneLights-36]
	_ = x[WagonCamp-37]
	_ = x[Windmill-40]
	_ = x[RandomTown-48]
	_ = x[RandomCastle-49]
	_ = x[WatchTower-58]
	_ = x[TreeHouse-59]
	_ = x[TreeCity-60]
	_ = x[Ruins-61]
	_ = x[Fort-62]
	_ = x[TradingPost-63]
	_ = x[AbandonedMine-64]
	_ = x[TreeOfKnowledge-68]
	_ = x[DoctorHut-69]
	_ = x[Temple-70]
	_ = x[HillFort-71]
	_ = x[HalflingHole-72]
	_ = x[MercenaryCamp-73]
	_ = x[Pyramid-76]
	_ = x[CityOfTheDead-77]
	_ = x[Excavation-78]
	_ = x[Sphinx-79]
	_ = x[ArtesianSpring-82]
	_ = x[TrollBridge-83]
	_ = x[WitchsHut-85]
	_ = x[Xanadu-86]
	_ = x[Cave-87]
	_ = x[MagellansMaps-89]
	_ = x[DerelictShip-91]
	_ = x[MagicWell-94]
	_ = x[ObservationTower-96]
	_ = x[FreemansFoundry-97]
	_ = x[Arena-114]
	_ = x[BarrowMounds-115]
	_ = x[Mermaid-116]
	_ = x[Sirens-117]
	_ = x[HutMagi-118]
	_ = x[EyeMagi-119]
	_ = x[TravellerTent-120]
	_ = x[Jail-123]
	_ = x[FireAltar-124]
	_ = x[AirAltar-125]
	_ = x[EarthAltar-126]
	_ = x[WaterAltar-127]
	_ = x[AlchemyTower-234]
	_ = x[Stables-235]
}

const _Object_name = "AlchemyLabSkeletonDaemonCaveFaerieRingGazeboGraveyardArchersHouseDwarfCottagePeasantHutDragonCityLightHouseWaterWheelMinesObeliskOasisSawmillOracleShipWreckDesertTentCastleStoneLightsWagonCampWindmillRandomTownRandomCastleWatchTowerTreeHouseTreeCityRuinsFortTradingPostAbandonedMineTreeOfKnowledgeDoctorHutTempleHillFortHalflingHoleMercenaryCampPyramidCityOfTheDeadExcavationSphinxArtesianSpringTrollBridgeWitchsHutXanaduCaveMagellansMapsDerelictShipMagicWellObservationTowerFreemansFoundryArenaBarrowMoundsMermaidSirensHutMagiEyeMagiTravellerTentJailFireAltarAirAltarEarthAltarWaterAltarAlchemyTowerStables"

var _Object_map = map[Object]string{
	1:   _Object_name[0:10],
	4:   _Object_name[10:18],
	5:   _Object_name[18:28],
	7:   _Object_name[28:38],
	10:  _Object_name[38:44],
	12:  _Object_name[44:53],
	13:  _Object_name[53:65],
	15:  _Object_name[65:77],
	16:  _Object_name[77:87],
	20:  _Object_name[87:97],
	21:  _Object_name[97:107],
	22:  _Object_name[107:117],
	23:  _Object_name[117:122],
	25:  _Object_name[122:129],
	26:  _Object_name[129:134],
	29:  _Object_name[134:141],
	30:  _Object_name[141:147],
	32:  _Object_name[147:156],
	34:  _Object_name[156:166],
	35:  _Object_name[166:172],
	36:  _Object_name[172:183],
	37:  _Object_name[183:192],
	40:  _Object_name[192:200],
	48:  _Object_name[200:210],
	49:  _Object_name[210:222],
	58:  _Object_name[222:232],
	59:  _Object_name[232:241],
	60:  _Object_name[241:249],
	61:  _Object_name[249:254],
	62:  _Object_name[254:258],
	63:  _Object_name[258:269],
	64:  _Object_name[269:282],
	68:  _Object_name[282:297],
	69:  _Object_name[297:306],
	70:  _Object_name[306:312],
	71:  _Object_name[312:320],
	72:  _Object_name[320:332],
	73:  _Object_name[332:345],
	76:  _Object_name[345:352],
	77:  _Object_name[352:365],
	78:  _Object_name[365:375],
	79:  _Object_name[375:381],
	82:  _Object_name[381:395],
	83:  _Object_name[395:406],
	85:  _Object_name[406:415],
	86:  _Object_name[415:421],
	87:  _Object_name[421:425],
	89:  _Object_name[425:438],
	91:  _Object_name[438:450],
	94:  _Object_name[450:459],
	96:  _Object_name[459:475],
	97:  _Object_name[475:490],
	114: _Object_name[490:495],
	115: _Object_name[495:507],
	116: _Object_name[507:514],
	117: _Object_name[514:520],
	118: _Object_name[520:527],
	119: _Object_name[527:534],
	120: _Object_name[534:547],
	123: _Object_name[547:551],
	124: _Object_name[551:560],
	125: _Object_name[560:568],
	126: _Object_name[568:578],
	127: _Object_name[578:588],
	234: _Object_name[588:600],
	235: _Object_name[600:607],
}

func (i Object) String() string {
	if str, ok := _Object_map[i]; ok {
		return str
	}
	return strconv.FormatInt(int64(i), 10)
}
