// Code generated by "stringer -type=Object"; DO NOT EDIT.

package mp2

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[XXX-0]
	_ = x[AlchemyLab-1]
	_ = x[Skeleton-4]
	_ = x[DaemonCave-5]
	_ = x[FaerieRing-7]
	_ = x[Gazebo-10]
	_ = x[Graveyard-12]
	_ = x[ArchersHouse-13]
	_ = x[DwarfCottage-15]
	_ = x[PeasantHut-16]
	_ = x[DragonCity-20]
	_ = x[LightHouse-21]
	_ = x[WaterWheel-22]
	_ = x[Mines-23]
	_ = x[Obelisk-25]
	_ = x[Oasis-26]
	_ = x[Coast1-28]
	_ = x[Sawmill-29]
	_ = x[Oracle-30]
	_ = x[ShipWreck-32]
	_ = x[DesertTent-34]
	_ = x[Castle-35]
	_ = x[StoneLights-36]
	_ = x[WagonCamp-37]
	_ = x[Windmill-40]
	_ = x[RandomTown-48]
	_ = x[RandomCastle-49]
	_ = x[Coast2-56]
	_ = x[Coast3-57]
	_ = x[WatchTower-58]
	_ = x[TreeHouse-59]
	_ = x[TreeCity-60]
	_ = x[Ruins-61]
	_ = x[Fort-62]
	_ = x[TradingPost-63]
	_ = x[AbandonedMine-64]
	_ = x[TreeOfKnowledge-68]
	_ = x[DoctorHut-69]
	_ = x[Temple-70]
	_ = x[HillFort-71]
	_ = x[HalflingHole-72]
	_ = x[MercenaryCamp-73]
	_ = x[Pyramid-76]
	_ = x[CityOfTheDead-77]
	_ = x[Excavation-78]
	_ = x[Sphinx-79]
	_ = x[Coast4-81]
	_ = x[ArtesianSpring-82]
	_ = x[TrollBridge-83]
	_ = x[WitchsHut-85]
	_ = x[Xanadu-86]
	_ = x[Cave-87]
	_ = x[MagellansMaps-89]
	_ = x[DerelictShip-91]
	_ = x[MagicWell-94]
	_ = x[ObservationTower-96]
	_ = x[FreemansFoundry-97]
	_ = x[Coast5-99]
	_ = x[Coast6-100]
	_ = x[Coast7-101]
	_ = x[Coast8-102]
	_ = x[Coast9-103]
	_ = x[Coast10-104]
	_ = x[Coast11-105]
	_ = x[Coast12-106]
	_ = x[Coast13-107]
	_ = x[Coast14-108]
	_ = x[Coast15-109]
	_ = x[Coast16-110]
	_ = x[Coast17-111]
	_ = x[Coast18-112]
	_ = x[Coast19-113]
	_ = x[Arena-114]
	_ = x[BarrowMounds-115]
	_ = x[Mermaid-116]
	_ = x[Sirens-117]
	_ = x[HutMagi-118]
	_ = x[EyeMagi-119]
	_ = x[TravellerTent-120]
	_ = x[Jail-123]
	_ = x[FireAltar-124]
	_ = x[AirAltar-125]
	_ = x[EarthAltar-126]
	_ = x[WaterAltar-127]
	_ = x[Coast20-128]
	_ = x[Coast21-129]
	_ = x[Coast22-130]
	_ = x[Coast23-131]
	_ = x[Coast24-132]
	_ = x[Coast25-133]
	_ = x[Coast26-134]
	_ = x[Coast27-135]
	_ = x[Coast28-136]
	_ = x[Coast29-137]
	_ = x[Coast30-138]
	_ = x[Coast31-139]
	_ = x[Coast32-140]
	_ = x[Coast33-141]
	_ = x[Coast34-142]
	_ = x[Coast35-143]
	_ = x[Coast36-144]
	_ = x[Coast37-147]
	_ = x[Coast38-148]
	_ = x[Coast39-149]
	_ = x[Coast40-150]
	_ = x[Coast41-151]
	_ = x[Coast42-152]
	_ = x[Coast43-153]
	_ = x[Coast44-154]
	_ = x[Coast45-155]
	_ = x[Coast46-157]
	_ = x[Coast47-158]
	_ = x[Coast48-159]
	_ = x[Coast49-160]
	_ = x[Coast50-162]
	_ = x[Coast51-163]
	_ = x[Coast52-164]
	_ = x[Coast53-165]
	_ = x[Coast54-167]
	_ = x[Coast55-168]
	_ = x[Coast56-169]
	_ = x[Coast57-171]
	_ = x[Coast58-172]
	_ = x[Coast59-173]
	_ = x[Coast60-174]
	_ = x[Coast61-175]
	_ = x[Coast62-176]
	_ = x[Coast63-177]
	_ = x[Coast64-179]
	_ = x[Coast65-180]
	_ = x[Coast66-181]
	_ = x[Coast67-182]
	_ = x[Coast68-183]
	_ = x[Coast69-186]
	_ = x[Coast70-187]
	_ = x[Coast71-188]
	_ = x[Coast72-189]
	_ = x[Coast73-190]
	_ = x[Coast74-191]
	_ = x[Coast75-192]
	_ = x[Coast76-193]
	_ = x[Coast77-194]
	_ = x[Coast78-195]
	_ = x[Coast79-196]
	_ = x[Coast80-197]
	_ = x[Coast81-198]
	_ = x[Coast82-199]
	_ = x[Coast83-200]
	_ = x[Coast84-201]
	_ = x[Coast85-202]
	_ = x[Coast86-203]
	_ = x[Coast87-204]
	_ = x[Coast88-205]
	_ = x[Coast89-206]
	_ = x[Coast90-207]
	_ = x[Coast91-208]
	_ = x[Coast92-210]
	_ = x[Coast93-211]
	_ = x[Coast94-212]
	_ = x[Coast95-213]
	_ = x[Coast96-214]
	_ = x[Coast97-215]
	_ = x[Coast98-216]
	_ = x[Coast99-217]
	_ = x[Coast100-218]
	_ = x[Coast101-219]
	_ = x[Coast102-220]
	_ = x[Coast103-221]
	_ = x[Coast104-222]
	_ = x[Coast105-223]
	_ = x[Coast106-224]
	_ = x[Coast107-225]
	_ = x[Coast108-233]
	_ = x[AlchemyTower-234]
	_ = x[Stables-235]
	_ = x[Coast109-236]
	_ = x[Coast110-237]
	_ = x[Coast111-238]
	_ = x[Coast112-239]
	_ = x[Coast113-240]
	_ = x[Coast114-241]
	_ = x[Coast115-242]
	_ = x[Coast116-243]
	_ = x[Coast117-244]
	_ = x[Coast128-245]
	_ = x[Coast129-246]
	_ = x[Coast130-247]
	_ = x[Coast131-248]
	_ = x[Coast132-251]
	_ = x[Coast133-252]
	_ = x[Coast134-253]
	_ = x[Coast135-254]
	_ = x[Coast136-255]
}

const _Object_name = "XXXAlchemyLabSkeletonDaemonCaveFaerieRingGazeboGraveyardArchersHouseDwarfCottagePeasantHutDragonCityLightHouseWaterWheelMinesObeliskOasisCoast1SawmillOracleShipWreckDesertTentCastleStoneLightsWagonCampWindmillRandomTownRandomCastleCoast2Coast3WatchTowerTreeHouseTreeCityRuinsFortTradingPostAbandonedMineTreeOfKnowledgeDoctorHutTempleHillFortHalflingHoleMercenaryCampPyramidCityOfTheDeadExcavationSphinxCoast4ArtesianSpringTrollBridgeWitchsHutXanaduCaveMagellansMapsDerelictShipMagicWellObservationTowerFreemansFoundryCoast5Coast6Coast7Coast8Coast9Coast10Coast11Coast12Coast13Coast14Coast15Coast16Coast17Coast18Coast19ArenaBarrowMoundsMermaidSirensHutMagiEyeMagiTravellerTentJailFireAltarAirAltarEarthAltarWaterAltarCoast20Coast21Coast22Coast23Coast24Coast25Coast26Coast27Coast28Coast29Coast30Coast31Coast32Coast33Coast34Coast35Coast36Coast37Coast38Coast39Coast40Coast41Coast42Coast43Coast44Coast45Coast46Coast47Coast48Coast49Coast50Coast51Coast52Coast53Coast54Coast55Coast56Coast57Coast58Coast59Coast60Coast61Coast62Coast63Coast64Coast65Coast66Coast67Coast68Coast69Coast70Coast71Coast72Coast73Coast74Coast75Coast76Coast77Coast78Coast79Coast80Coast81Coast82Coast83Coast84Coast85Coast86Coast87Coast88Coast89Coast90Coast91Coast92Coast93Coast94Coast95Coast96Coast97Coast98Coast99Coast100Coast101Coast102Coast103Coast104Coast105Coast106Coast107Coast108AlchemyTowerStablesCoast109Coast110Coast111Coast112Coast113Coast114Coast115Coast116Coast117Coast128Coast129Coast130Coast131Coast132Coast133Coast134Coast135Coast136"

var _Object_map = map[Object]string{
	0:   _Object_name[0:3],
	1:   _Object_name[3:13],
	4:   _Object_name[13:21],
	5:   _Object_name[21:31],
	7:   _Object_name[31:41],
	10:  _Object_name[41:47],
	12:  _Object_name[47:56],
	13:  _Object_name[56:68],
	15:  _Object_name[68:80],
	16:  _Object_name[80:90],
	20:  _Object_name[90:100],
	21:  _Object_name[100:110],
	22:  _Object_name[110:120],
	23:  _Object_name[120:125],
	25:  _Object_name[125:132],
	26:  _Object_name[132:137],
	28:  _Object_name[137:143],
	29:  _Object_name[143:150],
	30:  _Object_name[150:156],
	32:  _Object_name[156:165],
	34:  _Object_name[165:175],
	35:  _Object_name[175:181],
	36:  _Object_name[181:192],
	37:  _Object_name[192:201],
	40:  _Object_name[201:209],
	48:  _Object_name[209:219],
	49:  _Object_name[219:231],
	56:  _Object_name[231:237],
	57:  _Object_name[237:243],
	58:  _Object_name[243:253],
	59:  _Object_name[253:262],
	60:  _Object_name[262:270],
	61:  _Object_name[270:275],
	62:  _Object_name[275:279],
	63:  _Object_name[279:290],
	64:  _Object_name[290:303],
	68:  _Object_name[303:318],
	69:  _Object_name[318:327],
	70:  _Object_name[327:333],
	71:  _Object_name[333:341],
	72:  _Object_name[341:353],
	73:  _Object_name[353:366],
	76:  _Object_name[366:373],
	77:  _Object_name[373:386],
	78:  _Object_name[386:396],
	79:  _Object_name[396:402],
	81:  _Object_name[402:408],
	82:  _Object_name[408:422],
	83:  _Object_name[422:433],
	85:  _Object_name[433:442],
	86:  _Object_name[442:448],
	87:  _Object_name[448:452],
	89:  _Object_name[452:465],
	91:  _Object_name[465:477],
	94:  _Object_name[477:486],
	96:  _Object_name[486:502],
	97:  _Object_name[502:517],
	99:  _Object_name[517:523],
	100: _Object_name[523:529],
	101: _Object_name[529:535],
	102: _Object_name[535:541],
	103: _Object_name[541:547],
	104: _Object_name[547:554],
	105: _Object_name[554:561],
	106: _Object_name[561:568],
	107: _Object_name[568:575],
	108: _Object_name[575:582],
	109: _Object_name[582:589],
	110: _Object_name[589:596],
	111: _Object_name[596:603],
	112: _Object_name[603:610],
	113: _Object_name[610:617],
	114: _Object_name[617:622],
	115: _Object_name[622:634],
	116: _Object_name[634:641],
	117: _Object_name[641:647],
	118: _Object_name[647:654],
	119: _Object_name[654:661],
	120: _Object_name[661:674],
	123: _Object_name[674:678],
	124: _Object_name[678:687],
	125: _Object_name[687:695],
	126: _Object_name[695:705],
	127: _Object_name[705:715],
	128: _Object_name[715:722],
	129: _Object_name[722:729],
	130: _Object_name[729:736],
	131: _Object_name[736:743],
	132: _Object_name[743:750],
	133: _Object_name[750:757],
	134: _Object_name[757:764],
	135: _Object_name[764:771],
	136: _Object_name[771:778],
	137: _Object_name[778:785],
	138: _Object_name[785:792],
	139: _Object_name[792:799],
	140: _Object_name[799:806],
	141: _Object_name[806:813],
	142: _Object_name[813:820],
	143: _Object_name[820:827],
	144: _Object_name[827:834],
	147: _Object_name[834:841],
	148: _Object_name[841:848],
	149: _Object_name[848:855],
	150: _Object_name[855:862],
	151: _Object_name[862:869],
	152: _Object_name[869:876],
	153: _Object_name[876:883],
	154: _Object_name[883:890],
	155: _Object_name[890:897],
	157: _Object_name[897:904],
	158: _Object_name[904:911],
	159: _Object_name[911:918],
	160: _Object_name[918:925],
	162: _Object_name[925:932],
	163: _Object_name[932:939],
	164: _Object_name[939:946],
	165: _Object_name[946:953],
	167: _Object_name[953:960],
	168: _Object_name[960:967],
	169: _Object_name[967:974],
	171: _Object_name[974:981],
	172: _Object_name[981:988],
	173: _Object_name[988:995],
	174: _Object_name[995:1002],
	175: _Object_name[1002:1009],
	176: _Object_name[1009:1016],
	177: _Object_name[1016:1023],
	179: _Object_name[1023:1030],
	180: _Object_name[1030:1037],
	181: _Object_name[1037:1044],
	182: _Object_name[1044:1051],
	183: _Object_name[1051:1058],
	186: _Object_name[1058:1065],
	187: _Object_name[1065:1072],
	188: _Object_name[1072:1079],
	189: _Object_name[1079:1086],
	190: _Object_name[1086:1093],
	191: _Object_name[1093:1100],
	192: _Object_name[1100:1107],
	193: _Object_name[1107:1114],
	194: _Object_name[1114:1121],
	195: _Object_name[1121:1128],
	196: _Object_name[1128:1135],
	197: _Object_name[1135:1142],
	198: _Object_name[1142:1149],
	199: _Object_name[1149:1156],
	200: _Object_name[1156:1163],
	201: _Object_name[1163:1170],
	202: _Object_name[1170:1177],
	203: _Object_name[1177:1184],
	204: _Object_name[1184:1191],
	205: _Object_name[1191:1198],
	206: _Object_name[1198:1205],
	207: _Object_name[1205:1212],
	208: _Object_name[1212:1219],
	210: _Object_name[1219:1226],
	211: _Object_name[1226:1233],
	212: _Object_name[1233:1240],
	213: _Object_name[1240:1247],
	214: _Object_name[1247:1254],
	215: _Object_name[1254:1261],
	216: _Object_name[1261:1268],
	217: _Object_name[1268:1275],
	218: _Object_name[1275:1283],
	219: _Object_name[1283:1291],
	220: _Object_name[1291:1299],
	221: _Object_name[1299:1307],
	222: _Object_name[1307:1315],
	223: _Object_name[1315:1323],
	224: _Object_name[1323:1331],
	225: _Object_name[1331:1339],
	233: _Object_name[1339:1347],
	234: _Object_name[1347:1359],
	235: _Object_name[1359:1366],
	236: _Object_name[1366:1374],
	237: _Object_name[1374:1382],
	238: _Object_name[1382:1390],
	239: _Object_name[1390:1398],
	240: _Object_name[1398:1406],
	241: _Object_name[1406:1414],
	242: _Object_name[1414:1422],
	243: _Object_name[1422:1430],
	244: _Object_name[1430:1438],
	245: _Object_name[1438:1446],
	246: _Object_name[1446:1454],
	247: _Object_name[1454:1462],
	248: _Object_name[1462:1470],
	251: _Object_name[1470:1478],
	252: _Object_name[1478:1486],
	253: _Object_name[1486:1494],
	254: _Object_name[1494:1502],
	255: _Object_name[1502:1510],
}

func (i Object) String() string {
	if str, ok := _Object_map[i]; ok {
		return str
	}
	return "Object(" + strconv.FormatInt(int64(i), 10) + ")"
}
